### ISSUE TITLE
Add CI workflows to enhance the dev experience

### ISSUE THREAD

**Issue by umbynos** [arduino/go-properties-orderedmap#18]
Add some checks workflows to this repo to enhance the developer experience and to catch common problems:
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-license.md
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md
- https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-taskfiles.md

**Comment by MatteoPologruto** [comment]
Check workflows added in the following PRs:
- #19 
- #20 
- #21
